### ISSUE TITLE
(3.0 master and dev) basal y-axis cutoff in profile editor- minor

### ISSUE THREAD

**Issue by happygirlnyc70** [nightscout/AndroidAPS#1360]
Minor issue
Y axis cut off in profile editor for basal graph
Pixel 4a 5g Android 12

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new
![Screenshot_20220222-073503](https://user-images.githubusercontent.com/65825958/155133782-79f01ffe-661f-4248-af67-8da73e51897b.png)

**Comment by Andries-Smit** [comment]
@happygirlnyc70 it should be fixed it in https://github.com/nightscout/AndroidAPS/pull/1292
Could you confirm?

**Comment by happygirlnyc70** [comment]
@Andries-Smit it is still present in dev-a
![Screenshot_20220222-081714](https://user-images.githubusercontent.com/65825958/155140273-b72f8113-bbef-4b4c-9264-8514e403c70c.png)

**Comment by happygirlnyc70** [comment]
This is a minor cosmetic issue.  I will close this ticket.
