### ISSUE TITLE
Absolute Insuline negative

### ISSUE THREAD

**Issue by kamlox** [nightscout/AndroidAPS#1609]
Hello,

I encountered a bug where my absolute insule was negative. What should not be possible.
IOB was -2.5 it seems.
Profile has 0.9u/h
![1649704714546](https://user-images.githubusercontent.com/52744345/162814276-ea6da202-9c23-4a50-bd01-c0a022c61927.jpg)

Context:
This happened the night/morning after a day of drinking, and drinking too much.
First hypo in the night that I didn't feel, AAPS managed then hypo when I woke up and I had never seen an IOB that low.

Logs attached.
All log parameters were not checked

[AndroidAPS._2022-04-10_06-09-05_.2.log](https://github.com/nightscout/AndroidAPS/files/8467140/AndroidAPS._2022-04-10_06-09-05_.2.log)
[AndroidAPS._2022-04-10_06-09-05_.3.log](https://github.com/nightscout/AndroidAPS/files/8467143/AndroidAPS._2022-04-10_06-09-05_.3.log)
[AndroidAPS._2022-04-10_06-09-05_.4.log](https://github.com/nightscout/AndroidAPS/files/8467145/AndroidAPS._2022-04-10_06-09-05_.4.log)
[AndroidAPS._2022-04-10_06-09-05_.5.log](https://github.com/nightscout/AndroidAPS/files/8467147/AndroidAPS._2022-04-10_06-09-05_.5.log)

I can't get a history browser capture. It takes too long to load, I tried for 30 minutes without success

**Comment by kamlox** [comment]
Same problem today, but no alcohol.
There is no way my BIO is that low.
I've had this behavior for a week since I upgrade in the last dev.

![1649753130625](https://user-images.githubusercontent.com/52744345/162920786-0db62932-9742-4682-8689-3e31aa5fe6ce.jpg)

![1649753108823](https://user-images.githubusercontent.com/52744345/162920778-27af4556-6c90-421d-91d9-0c237f6c85a9.jpg)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8471303/AndroidAPS.log)

**Comment by kamlox** [comment]
> do yopu have screenshot of treatment - bolus & basal tab from the same time? some time before and after

Do you need more infos?

![1649755205196](https://user-images.githubusercontent.com/52744345/162927065-4b55a741-fb80-4f44-9807-9313352012de.jpg)
![1649755205207](https://user-images.githubusercontent.com/52744345/162927071-6ecb54ce-e171-412a-9cf1-f21700361ade.jpg)

**Comment by MilosKozak** [comment]
note. this seems to be the problem
![image](https://user-images.githubusercontent.com/11146458/162932721-f4c2c52e-b9b6-486d-a09b-240876d5a9df.png)

**Comment by mick711** [comment]
If i remember #robertrub have open an issue with the 4800mins

**Comment by kamlox** [comment]
> Its not stopping Zero temp and continues counting negative Insulin, same as in #1597. Even without the 4800 minutes it would go wrong

and like you I use the dash

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/b756a870887015f8af609e5915f2c03f47ee8518

**Comment by robertrub** [comment]
@MilosKozak Sorry but it is NOT solved. It still happens in dev-j. See issue #1706 

AndroidAPS 3.0.0.2-dev-j 
Build: 16d39421b7-2022.05.07-14:30
