### ISSUE TITLE
Strange watch face numbers and no arrow

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1707]
![20220507_114645.png](https://user-images.githubusercontent.com/76626474/167262302-dad99875-6679-4385-8bb0-10e98462a271.png)

AndroidAPS 3.0.0.2-dev-j 
Build: 16d39421b7-2022.05.07-14:30 

The watch app was built from dev-j. Can't remember if I built it from Tim's version or from Milos's dev.

**Comment by rICTx-T1D** [comment]
I dont can reproduce it... please restart your wear watch and maybe your phone.

**Comment by robertrub** [comment]
Tried, no change. All AAPS faces have the same problem, even the simple charging face.

We are both with French phones. Can there be an issue with the translation?

![screen.png](https://user-images.githubusercontent.com/76626474/167279605-8ee8e9d0-128c-4669-ba81-2142df2ca6e2.png)

**Comment by reijoahola-nightscout** [comment]
I have also the same "duplicate" problem, probably in all AAPS watcface types. The phone and watch have bees restarted several times. My watch is TicWatch Pro and Wear OS should be updated.

**Comment by fjpezuela** [comment]
I have the same problem over here. I also use a TicWatch Pro 3 GPS 1853. The "Tiles" don't work either.

Last build: 3.0.0.2-dev-j 96f095ce8

**Comment by robertrub** [comment]
@fjpezuela The tiles bug have been solved (?) in the last build. Did you build very recently ?

**Comment by reijoahola-nightscout** [comment]
I have the latest updates except that 1d old Crowdin update. I stiil see such problems with Tiles that some of the tools does not open. Also that often mentioned BG duplicate problem is still a problem. My watch is TicWatch Pro (2018 year model) with the updated Wear OS. The language in the watch and phone is English.

**Comment by robertrub** [comment]
@reijoahola-nightscout  You're correct about the tiles. They are visible but not functional :( Onlt the manual TT works on my TT tiles.

**Comment by fjpezuela** [comment]
@robertrub Yes, only manual TT works. The other 3 don't work yet with the latest build on watch and phone.

**Comment by vanelsberg** [comment]
Seeing the same.

**See https://github.com/nightscout/AndroidAPS/issues/1698:**

- Date display, including day name (as in THU, 5 MAY, 23:52) and week number:
It shows 52" (seconds, should be day name) and "52 MAY" (date)" (date show "minutes")

- Arrow on BG complication is not showing. Looks like it is showing the BG values wrapped to the next line?)

- Watch face settings (double-tap menue) crashes when scrolling to end

**Comment by vanelsberg** [comment]
> @fjpezuela The tiles bug have been solved (?) in the last build. Did you build very recently ?

Only the "Actions" tile. Other are still not working.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/e01647d496e405d3ae9617ae76f353147181ec02

**Comment by fjpezuela** [comment]
The main screen already shows the trend date and the glucose value does not appear twice. TT Tiles are still not working.

**Comment by reijoahola-nightscout** [comment]
Updated into the latest version. I have still this problem
- Watch face settings (double-tap menu) crashes when scrolling to end

**Comment by MilosKozak** [comment]
> Updated into the latest version. I have still this problem
> 
> * Watch face settings (double-tap menu) crashes when scrolling to end

uninstall from watch and install again

**Comment by reijoahola-nightscout** [comment]
> > Updated into the latest version. I have still this problem
> > 
> > * Watch face settings (double-tap menu) crashes when scrolling to end
> 
> uninstall from watch and install again

Thx, it corrected the setting problem.

**Comment by robertrub** [comment]
It is working but I have no idea what the last part |-  should say... 

![Screenshot_20220509-125029_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/167396040-25174fa9-802c-4d22-a879-09a3cc65facb.jpg)

![20220509_125119.png](https://user-images.githubusercontent.com/76626474/167396053-ffef4b55-b35d-44ac-9f96-f60a15e3038b.png)

**Comment by MilosKozak** [comment]
IOB fixed by https://github.com/nightscout/AndroidAPS/commit/7ef313e4aa22acd10571842f1dcfe36400c34fc7

**Comment by robertrub** [comment]
@MilosKozak I confirm, you've solved it :) The watchface is working well now.

![screen.png](https://user-images.githubusercontent.com/76626474/167474198-78a5b3a6-1708-42dd-b8a3-181f6bdcc824.png)

Next step, the tiles :)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/b437307157420a8abcdf46bee5981ecae739df71
