### ISSUE TITLE
Crusial bugs in 3.1.0

### ISSUE THREAD

**Issue by yhonatanb20** [nightscout/AndroidAPS#1937]
APP CRASHES CONSTANTLY WHEN SET TO LIGHT SKIN!!!
Also this new blue banner below the buttons is annoying, just stays somewhere in the middle.

**Comment by osodebailar** [comment]
Solved in dev

**Comment by yhonatanb20** [comment]
That doensn't help me. Can't understand why are you guys saying it. Usually things are solved in dev and then not solved in master.

**Comment by yhonatanb20** [comment]
Anything else to be aware of? Now getting crazy here, can't set up everything after the update.

**Comment by yhonatanb20** [comment]
Reinstall which version? 3.0.0.1 wouldn't work anymore, not setting up...

**Comment by osodebailar** [comment]
after complete removing you can install 3.1.0 again . the default is the dark theme and this works.
