### ISSUE TITLE
Tidepool is not receiving profile basal, only temp basal

### ISSUE THREAD

**Issue by campbellgl** [nightscout/AndroidAPS#3040]
3.2.0.1
Tidepool only receives temp basals. Profile basals show as 0.00 in Tidepool. In my logs from today, 2023-11-06 from 09:31 to 11:41 (16:31 to 18:41 GMT) my profile basal was running (0.85), but Tidepool shows zero basal.
[AndroidAPS._2023-11-05_17-00-43_.8.zip](https://github.com/nightscout/AndroidAPS/files/13274915/AndroidAPS._2023-11-05_17-00-43_.8.zip)
[AndroidAPS._2023-11-06_17-00-51_.0.zip](https://github.com/nightscout/AndroidAPS/files/13274916/AndroidAPS._2023-11-06_17-00-51_.0.zip)
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/13274917/AndroidAPS.log)

**Comment by CeDoMain** [comment]
I can confirm this problem!

**Comment by rmitchell7** [comment]
Same for me, does anyone know if there's a way I can get this working or who I can ask for help?

**Comment by TWilhoWI** [comment]
Also conform the problem

**Comment by ohjay73** [comment]
mine works fine using latest dev

**Comment by Bricki85** [comment]
Hi, I have the same Problem. I am on Version 3.2.0.2. Switches to Pump (Dash) recently. Therefore now it would be nice if I would see my Basal rates correctly.

@campbellgl did you solve your Problem somehow?

**Comment by campbellgl** [comment]
@Bricki85 I haven't tried in dev yet. Still not working in 3.2.0.4

**Comment by Bricki85** [comment]
Thanks @ohjay73 and @campbellgl
Will then wait for 3.3.0. I am not yet brave enough to go full dev yet.

**Comment by vanelsberg** [comment]
For me (latest dev) Tidepool only shows current ("automated") basal.
AFAIKT It does not support viewing the profile...

![image](https://github.com/nightscout/AndroidAPS/assets/45144129/714988bc-d7e8-44c7-bae8-75b99977ac6c)

**Comment by Bricki85** [comment]
I think you misunderstood me or the thread. What I see for you is a lot of zero TBRs and additional TBRs. Furthermore there are some gaps in our diagram where no blue line is. Rather few but some. At mine you can see it better:
![image](https://github.com/nightscout/AndroidAPS/assets/62853716/989030a1-7538-4176-b9b7-21fbd292310b)
There you see some blue lines with zero and then you see gaps where no blue line is. In those gaps my normal basal rate should be shown like for example 1.1U/h etc. But it seems Tidepool only shows the adjusted TBRs (deviating from the default basal rate in the profile).
I do not know your normal basal rate and if it is in the picture you uploaded. At least for me none of those are in there.

**Comment by ohjay73** [comment]
tidepool will only put in what your device is actually doing. Therefore if
you don't have a basal all day because SMB's are being used to replace
basal, you'll see nothing in basal.. same if only TBR's are used. It doesnt
care what your profile is, only what is actually being reported by the
device.

**Comment by Bricki85** [comment]
I have basal lets say for easier disussion 1,1U/h over the whole day. I see that I have zero TBRs and increased TBRs (those are in there) but all the gaps where there is no blue line there should be my default 1,1 basal rate. I see it in AAPS but not in Tidepool.

**Comment by vanelsberg** [comment]
> ... where there is no blue line there should be my default 1,1 basal rate. I see it in AAPS but not in Tidepool.
You assumption is wrong: when on zero-TBR there is no insulin administred. Ckeck your pump activity?
Basal rate in profile is insuline "at rest", AAPS algo will adjust for 0 to max U/hr basal every 5 minutes .....

**Comment by Bricki85** [comment]
> You assumption is wrong: when on zero-TBR there is no insulin administred. Ckeck your pump activity?
Basal rate in profile is insuline "at rest", AAPS algo will adjust for 0 to max U/hr basal every 5 minutes .....

If Zero TBR is set I get no Insulin. That is clear. And that AAPS adjusts the TBR is also fine.

I checked the export of my data from Tidepool and there is only as said the devivations from the default basal rate in there. Here is the corresponding Screenshot von AAPS. I would assume Tidepool and AAPS look similar.
![Screenshot_20240329_063227_AAPS](https://github.com/nightscout/AndroidAPS/assets/62853716/35dd3b90-3d1f-46ba-a71f-7e2a073a870c)

So if you compare both screenshots you will find that the default basal rate where AAPS did not adjust anything is missing.

So from my underestanding AAPS does not report the basal rate which is inside the profile to the backend? Does it work with Nightscout?

Maybe to make it even more clear if I have 1,1U/h in my profile for the whole day and I would not have one adjustment like zero TBR etc. Then I would see nothing inside Tidepool. No blue line whatsoever. And therefore my numbers in Tidepool for Basal would be 0 for the whole day. Whereever AAPS would say 26,40 at a whole.

**Comment by CeDoMain** [comment]
Hi guys. I understand what @Bricki85 means and I have the same issue. I have attached three pictures which show the same day. One from AAPS, Nightscout and Tidepool. For me its also clear that Tidepool doesnt show an active default Basal rate. It shows only the active non default rates. And for me and my doctor thats not good for comparing and analysing - e.g. something is missing which should obviously be there.

![aaps](https://github.com/nightscout/AndroidAPS/assets/9774882/c3152c33-66dd-4d71-984d-72f09d87b323)
![nightscout](https://github.com/nightscout/AndroidAPS/assets/9774882/da861e14-49a9-4838-99f4-e2a4c524927a)
![tidepool](https://github.com/nightscout/AndroidAPS/assets/9774882/fe0f6f3f-ac7b-4ea5-a03a-4ada228a0142)

**Comment by Bricki85** [comment]
Yeah here we can see it good, thanks for the images.
Nightscout actually does it correct somehow.
Question would be why. Does Nightscout get different data than Tidepool? Or does Nightscout just do more in the backend with the same data what Tidepool gets?
Maybe I dig into the code on the weekend if I find the time to see at least if the data upload is the same (I would assume it is. But you never know)

**Comment by CeDoMain** [comment]
Thank you @vanelsberg for sharing your diagrams! Its interesting what you have shown. For me NS definetly has some problems displaying zero temps. In my diagram there are also problems.

But also in your tidepool diagram I can see the default basal error which the TO descibes. When you carefully look at 4'clock in your aaps diagram, you can see dark blue areas at the start and end of the tbr curve. I marked these in red in the image below. and these dark blue areas show default rates active which are also not present in your tidepool diagram.
![image](https://github.com/nightscout/AndroidAPS/assets/9774882/418b285b-517c-4f26-90a8-8ef1873463e2)

**Comment by vanelsberg** [comment]
> But also in your tidepool diagram I can see the "default basal error" ....

I think this is about graph scaling and sampling. Once should not give to much weight to de graph details.
Mind that the graphs are intended to show "activity". For details, check your pump activity (NS treatments reporting)

**Comment by vanelsberg** [comment]
@janvitos @CeDoMain @campbellgl  Confirming: Also seeing this.

**Comment by janvitos** [comment]
> So the diagrams with the missing sections in tidepool also occur at your side?

Yes, exactly the same issue. Normal basals are missing and only temp basals are recorded. You can see the large gaps in basal in the screenshot below.

![markup_1000024159](https://github.com/nightscout/AndroidAPS/assets/10037804/febd38ca-426a-43d2-8ea2-b6a3d8e76b34)

**Comment by Stealthwick** [comment]
I am also experiencing this issue. It caused some confusion with the diabetes specialist who was trying to work out why so little basal was being delivered - turned out it was just unaccounted for due to only temp rates being counted.

Would love to see this get some attention as we're working hard in my country for our approach to be accepted by healthcare professionals!

**Comment by janvitos** [comment]
> It caused some confusion with the diabetes specialist who was trying to work out why so little basal was being delivered

This was my exact worry. My son's endo has access to his Tidepool and normally prints out the data of the last 2 weeks. But I'll have to use Nightscout and send them the reports myself now because of this bug. Hope it gets fixed in the near future!

**Comment by Stealthwick** [comment]
This issue remains unaddressed as far as I know. Is anyone currently working on a solution here? Fixing this would be helpful in keeping our HCPs onside!

**Comment by RApfelbeck** [comment]
I have the same problem with the current version 3.3.1.3. The normal basal rate is not displayed, only adjustments. The ticket has been around for a while. Is there anything I can do to help process the ticket?

![Image](https://github.com/user-attachments/assets/5bcd2ecc-72c4-41dd-a8af-ccd0b7b00802)

**Comment by RApfelbeck** [comment]
I took a look at the source of the TidepoolUploader. Here in UploadChunk only the getTemporaryBasalsStartingFromTimeToTime are fetched from the persistenceLayer and not merged with the normal values from the active profile. The currently visible result is therefore as expected according to the current source code. 

@MilosKozak According to Git history you were mainly active in this area, are you still active there? Would it be ok if we merge the data with the profile (in the history of the method I also see something that could go in this direction). If you could give me a few tips on the anchor classes, I can also make a suggestion. 


![Image](https://github.com/user-attachments/assets/b59c6f9a-29f2-4db4-ab1d-6d7d04a07c91)

**Comment by RApfelbeck** [comment]
*corrected*

I took a look at the source of the TidepoolUploader. Here the getTemporaryBasalsStartingFromTimeToTime are retrieved from the persistenceLayer in UploadChunk and linked to the profile in fromTemporaryBasals. However, the number of entries in the loop / result seems to be determined by the list of temporary entries. 

@MilosKozak According to the Git history you were mainly active in this area, are you still active? Would it be ok from your point of view if we take the basic set from the profile and then merge it with the temporary data in the loop? If you could give me a few tips on the anchor classes, I can also make a suggestion

![Image](https://github.com/user-attachments/assets/454cd500-ffb6-4365-81fc-d1f9a0e5c455)

**Comment by vanelsberg** [comment]
> .. if we take the basic set from the profile and then merge it with the temporary data in the loop?

If I may jump in here?  I think it would be incorrect to assume that during any gaps in the TBR list the pump is running a basal rate from profile. Profile values are inly input for the algo are not used for setting basal rates.

Did you compare what is in Tidepool against what is logged under AAPS Treatments->Temp basal?
In my case (DASH) I only see few minor gabs, hardly noticeable. On close inspection in AAPS it looks like sometimes a TBR runs just a bit longer than the actual duration that was set according to the logged event.

![Image](https://github.com/user-attachments/assets/bd9b4011-3664-450a-802a-3c37d9fcc579)

I think the gabs we are seeing in Tidepool are from uploading the TBR events into Tidepool where it apparently is showing the TBR based on the duration as reported in the event data uploaded.

__Assuming TBR's sometimes run longer than the duration set_, a possible fix could be extending the end of a TBR event to the start of the next TBR event (=extending duration) in the list (assuming setting a new TBR was just delayed)_

@MilosKozak Interested in your insights in this.

**Comment by vanelsberg** [comment]
As a follow up, question is what is causing these "gabs" in the list of TBT events:
- Temporary pump disconnects?
- AAPS to busy or low phone performance preventing AAPS to timely picking up TBR commands causing a TBR to run longer than the original duration intended?

**Comment by Stealthwick** [comment]
I’ve run side by side comparisons with Nightscout and AAPS. Some of my
screenshots are above.

The gaps occur whenever the pump is running profile basal rate rather than
temp basal. You can verify this by suspending the loop and noting the
absence of basal Tidepool.

**Comment by RApfelbeck** [comment]
yes, for tidepool I can confirm the behavior, only temporary basal values are transferred, the total basal insulin amount in the display also reflects this. It is particularly good to see in the openLoop with few basal rate adjustments, then long stretches of basal data are missing. 

![Image](https://github.com/user-attachments/assets/85688aa8-0b10-4aee-a2dc-35d0d4deaeb4)

**Comment by RApfelbeck** [comment]
When I look at the overview in the app, the graphics are correct. The chats for the basal rate are divided into 4 series: base, temp, basalLine and absolute. The calculation of absulute is also based on base and if a temp is active, this is transferred to absulute instead of base. In my opinion, a similar approach would also be necessary here to fill the areas without temp with base.

What do you think?

![Image](https://github.com/user-attachments/assets/3bdea78b-5dda-4854-8255-d33ffdb63e54)

**Comment by CeDoMain** [comment]
@RApfelbeck That sounds like a good idea! I want to remark that Nightscout has also Problems with the Basalrate. There is also Data missing - although with a different scheme. Probably there are more bugs with the basal transfer. @RApfelbeck Is the code you have shown in the datachain before nightscout or only before tidepool?

**Comment by RApfelbeck** [comment]
> [@RApfelbeck](https://github.com/RApfelbeck) Is the code you have shown in the datachain before nightscout or only before tidepool?

the source referenced in [comment-2616779013](https://github.com/nightscout/AndroidAPS/issues/3040#issuecomment-2616779013) only refers to the tidepool export.

the referenced source for the display in the overview of the app in [comment-2618994486](https://github.com/nightscout/AndroidAPS/issues/3040#issuecomment-2618994486) is generally valid and does not refer to an export

I have left/kept the relevant classes open as tabs in the screenshot. So you can quickly find the used references in android studio via class search with double shift

**Comment by Philoul** [comment]
> If I may jump in here? I think it would be incorrect to assume that during any gaps in the TBR list the pump is running a basal rate from profile. Profile values are only input for the algo are not used for setting basal rates.

@vanelsberg I don't agree with you (at least for Insight pump driver I know very well 😉) .
Basal rates included into user's profile are sent and recorded into the pump.
TBR duration you can see in treatment tab is the requested duration from AAPS while the TBR is running, but this duration is updated by the real TBR duration (received from the pump).

So all the duration you can see in treatments are the real duration got from the pump so between 2 TBRs, if you have a gap, profile basal is delivered by the pump.

If AAPS lost temporary communication with the pump, when communicatiln is re-established, the pump driver (at least Insight) read pump history and update all the events in treatment tab (real duration for TBRs, boluses or TBRs delivered directly from pump user interface...).

**Comment by Kopsida** [comment]
Tidepool feedback

**Comment by Kopsida** [comment]
This is the feedback I received from Tidepool regarding this issue:


##- Please type your reply above this line -##
Tidepool Logo
Your request (40997) has been updated. To add additional comments, you may reply to this email or use the link at the end of this email to view the ticket in our support portal.

	
Dave Cintron (Tidepool)

Jul 28, 2025, 09:48 CDT

Hi, thanks for your email and for reaching out to Tidepool Support.
 
Tidepool does not maintain the integration from AAPS to Tidepool. If data is not making it from your app, I would recommend communicating this issue to the developer(s) of the app and request they correct this problem.
 
You're not the first person to mention this and it's persisted for years, so I'm not sure whoever is maintaining the integration is interested in resolving it.
 
Sorry I can't be of more help. Let us know if you have any other questions.
Dave C.
Tidepool Support
support.tidepool.org
Tidepool Logo


	

Jul 28, 2025, 04:07 CDT

I upload my data from Android APS to Tidepool.

However, the reports in Tidepool don't show the basal profile, only the delivered or temporary basal amount.

The instructions on your website suggest that I should be able to see both values in the report,useful for ensuring that my basal rate are optimal.

Is there something I'm doing incorrectly?

Is be grateful for your help.



Link to this support ticket: https://support.tidepool.org/hc/requests/40997

[1RLP5K-LZ35D]
Many thanks for your prompt reply.
Show quoted text

**Comment by CeDoMain** [comment]
Hey guys, is there any chance to fix this issue? It shouldnt be very complicated and since tidepool ist one of two upload platforms it should be important for many people... (also its the free one)

**Comment by campbellgl** [comment]
This behavior remains in 3.4.0.0. Suspend loop or run in open loop, and profile basals show as zero in Tidepool:
<img width="874" height="586" alt="" src="https://github.com/user-attachments/assets/9834dfd2-921e-47ac-8760-5f1b2fa9337f" />

Tidepool does receive the profile, which contains the profile basal rates, but those are not filled into the the basal graph in between temp basals, so presumably the complete basal data must be uploaded independent of the profile information.
<img width="802" height="542" alt="" src="https://github.com/user-attachments/assets/57d58550-9bcc-4faf-9cfd-3b8510f848d3" />

**Comment by CeDoMain** [comment]
I can also confirm that this isnt fixed in 3.4.0.0. :( What can we do that this get fixed soon? Any chance to get the attention of the devs who knows the tidepool export? I know that @MilosKozak recently developed the OAuth for Tidepool. Does he know how to fix this?

**Comment by CeDoMain** [comment]
push

**Comment by MilosKozak** [comment]
push to tidepool

**Comment by CeDoMain** [comment]
> push to tidepool

sorry, but what do you @MilosKozak  mean by that?

**Comment by Philoul** [comment]
> sorry, but what do you @MilosKozak mean by that?

I will try to summarize, and sorry if I misunderstood the topic...
- in Tidepool you see TBRs running, but when you have no TBRs running you want to see profile basal rate, but you see 0 basal instead!

Now if you forget AAPS  the loop and focus on Tidepool features to synchronize pump data:
- you have a system sending profile, and boluses within Tidepool, but no or very few TBRs.
- in these situation, you want (of course) see your basal rates, but Tidepool only show 0 basal running, so Tidepool is not able to correctly show the basal running defined by the selected profile recorded into Tidepool ?

My understanding is the root cause of this issue is probably not within AAPS, but within Tidepool (I'm using Nightscout and it works correctly), so it should be opened and fixed on Tidepool side.

**Comment by loudestnoise** [comment]
Hi, Dave from the Tidepool Support team here. I'm quoted in a comment here a while back 😂.

I'm not on our engineering team, but I live with diabetes and use an Open-Source automated insulin delivery (OS-AID) app too. I help support people with diabetes use the Tidepool platform and we have heard from a number of AAPS folk like y'all about this basal issue.

Does looking at the developer documentation help understand what's going on here? 

https://tidepool.redocly.app/docs/device-data/data-types/basal/scheduled

It sounds like Tidepool gets temporary basal rates ([automated](https://tidepool.redocly.app/docs/device-data/data-types/basal/automated)) but isn't getting the scheduled ones. I'm wondering if that's because the way that data doesn't line up with what Tidepool's data model expects.

The other widely used OS-AID apps on iOS use a [Tidepool Service](https://github.com/LoopKit/TidepoolService) to send data and this helps it conform to Tidepool's data model.

**Comment by vanelsberg** [comment]
> It sounds like Tidepool gets temporary basal rates ([automated](https://tidepool.redocly.app/docs/device-data/data-types/basal/automated)) but isn't getting the scheduled ones.

Depending on interpretation, you could be right on that. And looking at Tidepools documentation this feels completely not logical to me. _Any pump will run basal insuline as set on the pumps profile unless instructed differently as a result of an event_ (be it manual or automated)

Tidepool has the users active basal profile so should assume basal rates are according to the user's profile unless set otherwise through:

* Automated Basals event (AID system changes basal rate)
* Suppressed Basals (AID stops basal rate, may be 0 TBR to prevent hypo)
* Scheduled Basals:
       _This is the sub-type of basal event that represents intervals of basal insulin delivery triggered by the pump itself according to the active basal schedule._

The first two run with a duration. So one would expect Tidepool to assume profile basal rates from user's profile when no automated or suppressed basal rate is active (past duration and no new basal set or pump stopped/disconnected).

I expect the use of Scheduled Basals is for temporally overruling the default user profile which Tidepool has through users default profile settings.

[And what about when the AID stops working (pump disconnected, AID out of range, system problem)?
Pump will continue doing profile basal so Tidepool should also automatically fall back as soon as basal durations set end.]

Your thoughts on this?

**Comment by PC809** [comment]
I do not have technical expertise, but I do have interest in this issue.  I have been looking at the link that Dave sent above to the developer documentation for Tidepool.  It seems to me that the trouble might be in the difference between the terms:

1) Basal Schedules ('basalSchedules'), which is listed under Pump Settings ('pumpSettings') and shows up under the Devices tab in Tidepool, 

and 

2) Scheduled Basals ('scheduled'), which is listed under Basal Insulin ('basal') and shows up as part of the graph under the Daily tab in Tidepool.  

Does that sound like it might be part of the puzzle?

I know that only a small percentage of AAPS users use Tidepool, and a small percentage of Tidepool users use AAPS.  So that makes us a minority in both ways.  But I hope that this issue isn't being dropped entirely.  We who are in that minority are very grateful for the work that has already been done in making it possible to use Tidepool with AAPS.  Many thanks!

**Comment by vanelsberg** [comment]
Problem is resolved in AAPS 4.0.0-dev, so available in next 4.0 release.
Graph now shows every basal change (with info on mouse-over), also for 0-TBR


<img width="892" height="114" alt="Image" src="https://github.com/user-attachments/assets/0077feeb-90c2-422f-8058-b5d6f8a176e7" />
