### ISSUE TITLE
[2.8.2 newest DEV] wear bolusing not possible

### ISSUE THREAD

**Issue by thomasmenges** [nightscout/AndroidAPS#382]
Since using the newest DEV version creating a bolus from the attached wear os watch isn't possible any more.

Switching back to the previous one and now the bolus support on the watch is active again

**Comment by MilosKozak** [comment]
fixed in dev

**Comment by thomasmenges** [comment]
I tested the issue in the latest DEV version. Problem isn't solved. If you want to bolus with a Wear OS smartwatch (Sony SWR50) it isn't possible anymore. Previous versions work fine.
