### ISSUE TITLE
[2.8.2.2-Dev] Insulin boluses and carbohydrates not syncing with xDrip +

### ISSUE THREAD

**Issue by fjpezuela** [nightscout/AndroidAPS#582]
Reporting bugs
--------------
When you add a treatment from the calculator, the data is synced correctly in Nightscout, however it is not synced with xDrip +.  No carbohydrate or bolus treatment is displayed in xDrip +.
![Screenshot_20210625-085127](https://user-images.githubusercontent.com/67511778/123382809-a976aa80-d592-11eb-845b-5a5877a1980c.jpg)
![Screenshot_20210625-085135](https://user-images.githubusercontent.com/67511778/123382816-aa0f4100-d592-11eb-9106-a3ecada9d498.jpg)
![Screenshot_20210625-085147](https://user-images.githubusercontent.com/67511778/123382818-aaa7d780-d592-11eb-9bcc-5c547af38143.jpg)

Version: 2.8.2.2-Dev Build 33047e478

**Comment by fjpezuela** [comment]
SMBs are also not displayed in xDrip +.  All this with version 2.8.2 worked without any problem

**Comment by MilosKozak** [comment]
hopefully fixed by https://github.com/nightscout/AndroidAPS/commit/272cdbbb0010a1acd9043de3629ce8131ef2d44b
remember it's still broadcasting only NSClient data ie only what is comming from NS

**Comment by hartlijn** [comment]
not fixed unfortunately (in todays dev version). 
xDrip always received treatments (smb, bolus, carb and even notes if I'not mistaken) directly from AAPS.

not sure what you @MilosKozak mean with 'only what is coming **from** NS'. I have both xDrip and AAPS configured to only uploadto  (and not dowload from) NS. To be able to have my system running not require an internet connection.

**Comment by fjpezuela** [comment]
It doesn't work for me either after recompiling the app

**Comment by MilosKozak** [comment]
sorry i was wrong. there was never direct AAPS -> xDrip broadcast. up to version 2.8.2 NSClient did broadcast data comming from NS. With new NSClient this functionality was removed
