### ISSUE TITLE
2.8.2.2 Dev : can't restart loop if stopped

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#637]
In 2.8.2 main, I can stop and restart the loop from the main page. In 2.8.2.2 dev, if I stop the loop, I need to go in the settings to reactivate the loop option.
When it is activated, I have a very strange 364days (deactivated ?) under the button.
![IMG-20210820-WA0000](https://user-images.githubusercontent.com/76626474/130197831-d0ff35b4-aee7-4965-a2a8-b83b25ea5e24.jpg)
![IMG-20210820-WA0001](https://user-images.githubusercontent.com/76626474/130197880-e78a73ab-72dc-4cea-93c3-7fd6e5ec7fc3.jpg)
![IMG-20210820-WA0002](https://user-images.githubusercontent.com/76626474/130197924-162f68e2-ee10-4515-a7af-e9667e6a385e.jpg)
![IMG-20210819-WA0002](https://user-images.githubusercontent.com/76626474/130197965-9b0f1d57-55aa-4263-8e8e-5549353c8bd4.jpg)

**Comment by robertrub** [comment]
Follow-up. It seems that from the user interface, I can only "downgrade" loop functions but not "upgrade". If I select _open loop_, then I can NOT select _closed loop_ from the main page. I need to go to the settings to activate closed loop. 
![image](https://user-images.githubusercontent.com/76626474/130218240-2ace68ec-e424-40ca-a446-d6d4a58547a3.png)
![image](https://user-images.githubusercontent.com/76626474/130218254-44a36cd6-d26b-4e5c-85b4-b5c91cbdf2d2.png)

**Comment by MichaelJohnSmith** [comment]
You can also select Low Glucose Suspend.  Then click the loop icon again to select Closed Loop.
Not correct, but slightly easier than going to settings!

**Comment by robertrub** [comment]
Nice try but no, it doesn't work of you turn off the loop. ;)

I never turn off the loop but I'm in testing stuff mode so I hit all the buttons available  :)

**Comment by Philoul** [comment]
I made a PR to fix bug of disable loop...
Concerning the direct switch from open loop to closed loop,  I have to look into constraints (closed loop is currently not aloud from open loop, even if relative objectives are passed...)

**Comment by Philoul** [comment]
I also prepared a commit (not currently pushed in the PR) to improve a bit user interface when loop is suspended or pump disconnected:
It will be possible to resume (respectively reconnect pump), or select a new duration.
My computer is off for 3 days, I'll update PR when I'll back home, but you can test current proposal and add comment if necessary...

**Comment by MilosKozak** [comment]
should be resolved now

**Comment by CaptainBalou** [comment]
That works for me. I can disconnect and reconnect my pump. In addition I can see that I'm now able to extend the disconnection time while I'm already disconnected. This is awesome!

**Comment by robertrub** [comment]
Hi Milos. It is partially solved. I can select "open loop" and come back to "closed loop" but I cannot stop the loop and then restart it from the main UI. Once the loop is stopped, I need to go in the config generator in order to reactivate the loop. I don't know if this is a bug or a feature ;)
Robert

**Comment by Philoul** [comment]
@robertrub can you share screenshot and explain the exact sequence of actions done from loop enabled to situation with issue ?
If I can reproduce it I'll be able to solve it...
Thanks

**Comment by robertrub** [comment]
![282_main](https://user-images.githubusercontent.com/76626474/133662923-6b8f0490-5f87-473c-8e17-10fc1b491a35.gif)
Above is from 2.8.2 Main. It is working ok.


https://user-images.githubusercontent.com/76626474/133663018-a7f6b787-076e-4c28-ba11-0dd7bc61031a.mp4

Above is from the latest dev. If I stop, it will only restart fron config.
![IMG-20210916-WA0005](https://user-images.githubusercontent.com/76626474/133663148-9eb02f1f-743a-4ee9-b1d2-e3e103063f9e.jpg)

**Comment by Philoul** [comment]
@robertrub if you test Dash branch you don't have latest commit included in dev branch yesterday (wait a little bit you'll probably have this fix soon...)

**Comment by robertrub** [comment]
Ok. If @Philoul says that it is fixed, them it is ;) I'd thought that DASH dev had the latest of dev...
