### ISSUE TITLE
[AAPS3.0_beta2] NSClient - io.socket.engineio.client.EngineIOException:xhr poll error - Seems to also have broken Nightscout

### ISSUE THREAD

**Issue by old-square-eyes** [nightscout/AndroidAPS#807]
Just installed beta 2 of NSClient 3.0. To get the build to work on my Mac M1, [I had to add a new version of "Room" to the gradle build file.](https://stackoverflow.com/questions/68922875/room-database-is-not-working-in-mac-book-pro-m1). Not sure if that's relevant.

NSClient opens on my S20 fine (had to uninstall prev version for it to install). I completed the wizard. Lots of errors in the logs.

Now my NS site has gone down, so this seems pretty nasty.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/25760491/139517176-b9807360-5a93-4c5a-8a8e-23109a6ac0c4.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/25760491/139517180-8a9a01e3-3f99-4b96-901b-0222916b7d6e.png">

**Comment by old-square-eyes** [comment]
Phew. I uninstalled NSClient, and reloaded the Nightscout Heroku Dynos and Nightscout came back.

**Comment by old-square-eyes** [comment]
Reinstalled NSClient and completed Wizard without NS creds. Then manually entered, and this time it started syncing status/BG. But eventually crashed the NS site again. Perhaps it's a internal server error at NS because it can't keep up with the sync?

**Comment by old-square-eyes** [comment]
Finally seems to be syncing. I turned off my two OpenAPS rigs and the NS API was able to keep up.

I see data in the history viewer. But not in the main graph. I'll see if there is more syncing. But I also can't select a Profile per https://github.com/nightscout/AndroidAPS/issues/808

**Comment by old-square-eyes** [comment]
I gave up. No plot on main graph. I went back to the old 2.X version and the plot immediately appeared.

**Comment by MilosKozak** [comment]
this is not enough info to be able help you

**Comment by MilosKozak** [comment]
where do you host NS?

**Comment by old-square-eyes** [comment]
Heroku / Atlas Mongo

**Comment by old-square-eyes** [comment]
@MilosKozak would you consider enabling local BG collection from xDrip? It's something I have wanted anyway to keep the watch face from NS lag.

**Comment by savek-cc** [comment]
@old-square-eyes did the event happen when adjusting the phone time for daylight savings time? (I saw the same errors but thought it might be due to altering time and timezone in anticipation for the time rewinding 1h (combo pump).

**Comment by old-square-eyes** [comment]
@savek-cc, I wasn't adjusting TZ, no. It's almost certainly a Heroku instance /dyno size. The API gets exhausted.

**Comment by betees82** [comment]
I faced the same problem. Finally downgraded to NS client 2.8 and works ok. I'm not sure, but it might been related with profile switch.
![image](https://user-images.githubusercontent.com/60583387/139842840-8aa43a0d-5446-4fc8-969b-fd7d4bc74216.png)

**Comment by old-square-eyes** [comment]
@MilosKozak is this in beta 3? I see no such option and a fresh install of beta 3 and I'm still getting the error. Also you mention NS upload. I'm pretty sure this is for data download. Sorry if I am stating the obvious.

**Comment by under-control** [comment]
same problem here, it worked like charm till yesterday, restarting does not help
and I'm using build for MedLink (instead of RileyLink)

![Screenshot_2021-11-06-10-26-26-741_info nightscout androidaps](https://user-images.githubusercontent.com/27731433/140605061-23cde5d8-f28d-4b74-9306-51ae86955e75.jpg)

**Comment by under-control** [comment]
Turns out it is caused by internet connection.

When connected to WiFi errors occurs, but then when switched to mobile Internet it connects right away and sends the data to NSClient.

**Comment by old-square-eyes** [comment]
That's interesting. I wonder if mobile data naturally has a slower request speed so NS doesn't get exhausted. I'll test. My WiFi is quite fast.

**Comment by old-square-eyes** [comment]
Fresh install / mobile data. It ran OK for a few minutes then same error for me.

**Comment by old-square-eyes** [comment]
Still having the no profile error too.

**Comment by MilosKozak** [comment]
OAPS doesn't support effective profile switches. you cannot make it working

**Comment by old-square-eyes** [comment]
@MilosKozak I think you may have misunderstood. I'm just trying to get NSclient working. Nothing to do with OpenAPS

**Comment by MilosKozak** [comment]
to activate profile you need data from AAPS
at least until there will be effective profie switch support in NS

**Comment by MilosKozak** [comment]
NSClient cannot create effective profile switch
but pumpcontrol could

**Comment by old-square-eyes** [comment]
@MilosKozak, I see. Well maybe I am mistaken. I assumed that my inability to select or otherwise apply a profile was the reason for no BG plot / NSClient IOB etc. Perhaps the issue is something else. Why then do I have no plot on the main screen? Per my screenshot and video above?

**Comment by under-control** [comment]
I think I found the source of problem and it's not just WiFi itself.

It was xiaomi setting that I turned off to not to restrict data usage, but it has to be ticked to work connect properly with NS.

![image](https://user-images.githubusercontent.com/27731433/140655619-e9a53cd7-61d5-414a-8e3c-3fccb137febf.png)

**Comment by old-square-eyes** [comment]
@under-control I'm on samsung and have the issue with WiFi and mobile data. I'm 99% sure it's a rate limit / server error due to too many reasons. Whatever setting you're using must simply be attenuation the rate or coincidentally working.

**Comment by old-square-eyes** [comment]
Confirming this seems fixed in beta 5. Rate limit seems to be doing its thing.

**Comment by paulosnsilva** [comment]
I'm having this issue. I'm using AAPS v. 3.0.0.1 with NS v.14.2.5 hosted on 10be.de.
On AAPS I have the "slowdown uploads" options active.
I've tried several restarts on NS and on my phone too.
I use NS to gather data and create medical reports for my doctor.

**Comment by paulosnsilva** [comment]
I've updated my AAPS to latest 3.1.0.3, but the issue persists.
Error: ERROR: io.socket.engineio.client.EngineIOException: xhr poll error.
I have 74896 pending records to submit. Maybe that is too much ? How do I reset it?

**Comment by paulosnsilva** [comment]
Just for future record, I got it to work again by resetting my NS db, and deleting all my data from AAPS, After clean install, it started to work as expected. Maybe my queue got a bit too fat.
