### ISSUE TITLE
[3.0-beta4] TT targets display the wrong value or units on Gear Tab

### ISSUE THREAD

**Issue by MichaelJohnSmith** [nightscout/AndroidAPS#867]
TT created from the Target button show the correct value but the wrong units
TT from automation shows the wrong value but the correct units

![Treatment - Gear](https://user-images.githubusercontent.com/55034864/140663120-e41fe551-ff1d-4c52-adc5-ef655e9c6558.jpg)

![Treatment - TT](https://user-images.githubusercontent.com/55034864/140663277-6f8b4a36-c5b8-4056-a3e9-e471faf52b6d.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/225797f430aa1324190a47de42d4957eda4b8364

**Comment by MichaelJohnSmith** [comment]
I got my errors swapped over above.
TT from target button now OK

However, in 3.0-beta5  TT from automation still shows the correct value but the wrong units

**Comment by MilosKozak** [comment]
thanks! https://github.com/nightscout/AndroidAPS/commit/c684f12aa7a42decaa260231b33e5b9e6dc95c3e
